File structure: Hash
Creation: 2022-01-15 18:52:52
Last modification: 2022-01-15 18:52:52
Schema: AN_BASE-INTEGER(4)|NM_GRANDE_AREA_CONHECIMENTO-VARCHAR(27)|NM_AREA_CONHECIMENTO-VARCHAR(42)|NM_SUBAREA_CONHECIMENTO-VARCHAR(59)|NM_ESPECIALIDADE-VARCHAR(57)|CD_AREA_AVALIACAO-INTEGER(2)|NM_AREA_AVALIACAO-VARCHAR(65)|CD_ENTIDADE_CAPES-INTEGER(8)|CD_ENTIDADE_EMEC-INTEGER(5)|SG_ENTIDADE_ENSINO-VARCHAR(20)|NM_ENTIDADE_ENSINO-VARCHAR(86)|CS_STATUS_JURIDICO-VARCHAR(10)|DS_DEPENDENCIA_ADMINISTRATIVA-VARCHAR(7)|DS_ORGANIZACAO_ACADEMICA-VARCHAR(51)|NM_REGIAO-VARCHAR(12)|SG_UF_PROGRAMA-VARCHAR(2)|NM_MUNICIPIO_PROGRAMA_IES-VARCHAR(25)|CD_PROGRAMA_IES-VARCHAR(13)|NM_PROGRAMA_IES-VARCHAR(104)|CD_CURSO_PPG-VARCHAR(13)|NM_CURSO-VARCHAR(110)|NM_GRAU-VARCHAR(22)|CD_CONCEITO_CURSO-INTEGER(1)|AN_INICIO_PREVISTO-INTEGER(4)|DS_SITUACAO_CURSO-VARCHAR(16)|DT_SITUACAO_CURSO-VARCHAR(5)|ID_ADD_FOTO_PROGRAMA_IES-INTEGER(6)|ID_ADD_FOTO_PROGRAMA-INTEGER(6)|
Number of records: 0
